#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const babel = require("@babel/core");

const root = path.resolve(__dirname, "..");
const sources = [
  "src/mpv/00_runtime.js",
  "src/mpv/05_config.js",
  "src/languages/lookup_character_policy.js",
  "src/languages/common.js",
  "src/languages/deinflection.js",
  "src/languages/japanese.js",
  "src/languages/english_yomitan_rules.js",
  "src/languages/english.js",
  "src/languages/french_yomitan_rules.js",
  "src/languages/french.js",
  "src/languages/german_yomitan_rules.js",
  "src/languages/german.js",
  "src/languages/chinese.js",
  "src/languages/korean.js",
  "src/languages/registry.js",
  "src/mpv/10_unicode.js",
  "src/mpv/20_media.js",
  "src/mpv/30_worker.js",
  "src/mpv/40_ass.js",
  "src/mpv/50_document.js",
  "src/mpv/60_popup.js",
  "src/mpv/70_services.js",
  "src/mpv/80_anki_transport.js",
  "src/mpv/81_anki_context.js",
  "src/mpv/82_anki_templates.js",
  "src/mpv/83_anki_duplicates.js",
  "src/mpv/84_anki_actions.js",
  "src/mpv/90_settings.js",
  "src/mpv/99_main.js",
];

const banner = [
  "// iinatan native mpv application; generated from src/mpv and src/languages.",
  "// Target: mpv 0.41+ MuJS / ECMAScript 5. Do not edit this file directly.",
  "(function () {",
  '"use strict";',
].join("\n");
const body = sources
  .map(
    (name) =>
      `\n// ---- ${name} ----\n${fs.readFileSync(path.join(root, name), "utf8")}`,
  )
  .join("\n");
const input = `${banner}${body}\n}());\n`;
const result = babel.transformSync(input, {
  filename: "iinatan.concat.js",
  babelrc: false,
  configFile: false,
  comments: true,
  compact: false,
  presets: [
    [
      "@babel/preset-env",
      { targets: { ie: "11" }, modules: false, loose: true },
    ],
  ],
});
const output = path.join(root, "scripts", "iinatan.js");
fs.writeFileSync(output, `${result.code}\n`);
console.log(
  `built ${path.relative(root, output)} from ${sources.length} sources`,
);
